# Generated by Django 3.2.6 on 2023-02-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='cancel_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
